# Generated by Django 4.1.1 on 2022-09-23 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('UUID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('CEO', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('date_field', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
