# Generated by Django 4.1.1 on 2022-09-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='UUID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
