# Generated by Django 4.1.1 on 2022-09-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_app', '0002_alter_company_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='UUID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
