# Generated by Django 4.1.1 on 2022-09-23 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company_app', '0003_alter_company_uuid'),
        ('Team_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='CompanyID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='Company_app.company'),
        ),
    ]
